# Generated by Django 2.2.3 on 2020-01-02 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('profile', models.CharField(blank=True, max_length=255, verbose_name='profile')),
                ('gender', models.CharField(blank=True, choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Secret')], default='2', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('pic', models.ImageField(blank=True, max_length=200, null=True, upload_to='users/images/', verbose_name='pic')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'db_table': 'api_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='投稿時間')),
                ('first_name', models.CharField(max_length=255, verbose_name='名前')),
                ('last_name', models.CharField(max_length=255, verbose_name='名字')),
                ('street_address1', models.CharField(max_length=255, verbose_name='住所１')),
                ('street_address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所２')),
                ('city', models.CharField(max_length=255, verbose_name='市町村区')),
                ('state', models.CharField(max_length=255, verbose_name='都道府県')),
                ('zip', models.CharField(max_length=255, verbose_name='郵便番号')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='顧客')),
            ],
            options={
                'verbose_name': '住所',
                'verbose_name_plural': '住所',
            },
        ),
    ]
