# Generated by Django 2.2.3 on 2019-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='front_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=' products/images/', verbose_name='表紙'),
        ),
    ]
