# Generated by Django 2.2.3 on 2019-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191208_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=' products/images/', verbose_name='画像'),
        ),
    ]
