# Generated by Django 2.2.3 on 2019-12-11 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20191211_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
        migrations.AddField(
            model_name='products',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_purchased', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_sold', to=settings.AUTH_USER_MODEL, verbose_name='販売者'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_onsale',
            field=models.BooleanField(default=True, verbose_name='販売中かどうか'),
        ),
    ]
