# Generated by Django 2.2.3 on 2019-12-12 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191211_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_purchased', to=settings.AUTH_USER_MODEL, verbose_name='購入者'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_onsale',
            field=models.BooleanField(default=True, verbose_name='販売中'),
        ),
    ]
